micronaut:
  application:
    name: demo
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
    dialect: MYSQL
    url: jdbc:mysql://localhost:3306/injection_poc
    username: root
    password: ''
netty:
  default:
    allocator:
      max-order: 3
